config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[new create show]
  resources :sessions, only: %i[new create destroy]
  resources :subs, only: %i[index new create edit update show] do
    resources :posts, only: %i[new create]
  end
  resources :posts, only: %i[show edit update] do
    resources :comments, only: %i[new]
  end
  resources :comments, only: %i[create show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, :author_id, :post_id, presence: true
  belongs_to :parent_comment,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    optional: true

  belongs_to :child_comment,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    optional: true

  belongs_to :post
  belongs_to :author,
    class_name: :User

  def latest_child
    comments = Comment.where(post_id: self.post_id)
    parent = self
    loop do
      child = comments.find_by(parent_comment_id: parent.id)
      break if child.nil?

      parent = child
    end
    parent
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :author_id, presence: true

  has_many :posts_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, :through => :posts_subs
  
  has_many :comments
  belongs_to :author,
    class_name: :User

  def comments_by_parent_id
    all_comments = comments.includes(:author)
    sorted_hash = Hash.new { |h, k| h[k] = {} }
    all_comments.each do |comment|
      sorted_hash[comment.parent_comment_id] = [
        comment_hash(comment)
      ]
    end 
    sorted_hash
  end

  private

  def comment_hash(comment)
    { 
      id: comment.id, 
      parent_comment_id: comment.parent_comment_id,
      author: comment.author.username,
      created_at: comment.created_at,
      content: comment.content }
  end
end

app/models/posts_sub.rb
class PostsSub < ApplicationRecord
  validates :post, presence: true
  validates :sub_id, presence: true, uniqueness: { scope: :post_id }

  belongs_to :post,
    foreign_key: :post_id
  belongs_to :sub,
    foreign_key: :sub_id
end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :moderator_id, presence: true
  has_many :posts_subs
  has_many :posts, :through => :posts_subs

  belongs_to :moderator,
    class_name: :User
end

app/models/user.rb
require 'securerandom'

class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  before_commit :ensure_session_token

  has_many :comments,
    foreign_key: :author_id
    
  has_many :posts,
    foreign_key: :author_id
    
  has_many :subs,
    class_name: :Sub,
    foreign_key: :moderator_id
    
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
    self.save
  end

  def self.generate_session_token
    SecureRandom.base64
  end 
 
  def password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = User.generate_session_token
    self.save
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.password?(password) ? (user) : (nil)
  end

  attr_reader :password

  def ensure_session_token
    self.session_token ||= User.generate_session_token
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
  
  def logged_in?
    !!current_user
  end

  def login(user)
    user.reset_session_token
    session[:session_token] = user.session_token
  end

  def logout(user)
    user.reset_session_token
    session[:session_token] = ''
  end

  def ensure_login
    unless logged_in?
      flash[:errors] = 'Must log in.'
      redirect_to new_session_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post_id = params[:post_id]
    render :new
  end

  def create
    comment = Comment.new(comment_params)
    comment.author_id = current_user.id

    if comment.save
      redirect_to post_url(comment.post)
    else
      flash.now[:error] = 'Must contain a comment.'
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
    @all_comments = Comment.includes(:author).where(post_id: @comment.post_id)
    render :show
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end

  def comment_chain(comment)
  
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_login, except: %i[show]
  before_action :ensure_author, only: %i[edit update]
  def new
    render :new
  end

  def create
    post = Post.new(post_params)
    post.author_id = current_user.id
    post.sub_ids = params[:sub_id]
    if post.save
      redirect_to post_url(post)
    else
      flash[:errors] = 'Invalid post. Please try again.'
      redirect_to new_sub_post_url(post.sub_ids.first)
    end
  end

  def show
    @post = Post.find(params[:id])
    @all_comments = @post.comments_by_parent_id
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    post = Post.find(params[:id])

    if post.update(post_params)
      redirect_to post_url(post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def ensure_author
    post = Post.find(params[:id])
    if !logged_in? || post.author_id != current_user.id
      flash[:errors] = 'You aren\'t authorized to do this.'
      redirect_to subs_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    
    if user.nil?
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    else
      login(user)
      redirect_to user_url(user)
    end
  end
  

  def destroy
    @user = User.find(params[:id])
    if @user
      logout(@user)
      redirect_to subs_url
    end
  end

  private
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_login, only: :create
  before_action :is_moderator?, only: %i[edit update]
  def index
    render :index
  end

  def new
    render :new
  end

  def create
    sub = Sub.new(sub_params)
    sub.moderator_id = current_user.id
    if sub.save
      redirect_to sub_url(sub)
    else
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    sub = Sub.find(params[:id])
    if sub.update_attributes(sub_params)
      redirect_to sub_url(sub)
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def is_moderator?
    sub = Sub.find(params[:id])
    if logged_in? && sub.moderator_id == current_user.id
      true
    else
      redirect_to subs_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = 'Invalid Params'
      render :new
    end
  end

  def show
    render :show
  end

  private

  def user_params
    
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
Posted by: <%= comment[:author] %>
<p><%= comment[:content] %></p>
<section class='comment-info'>
  Posted at: <%= comment[:created_at] %>
</section>

app/views/comments/new.html.erb
<form method='post' action='<%= comments_url %>'>
  <input 
    type='hidden'
    name='authenticity_token' 
    value='<%= form_authenticity_token%>'>
  <textarea name='[comment][content]' id='comment'></textarea>
  <input type='hidden' name=[comment][post_id] value='<%= @post_id %>'>
  <button>Comment</button>
</form>

app/views/comments/show.html.erb
<ul class='comment-chain'>
  <li>
    <%= render partial: "comments/comment", object: @comment %>
    <% parent = @comment%>
    <% loop_counter = 0 %>
    <% loop do %>
      <% loop_counter += 1 %>
      <% child = @all_comments.find do |comment| %>
        <% comment.parent_comment_id == parent.id %>
      <% end %>
      <% if child %>
        <ul>
          <li>
            <%= render partial: "comments/comment", locals: {comment: child } %>
            <% parent = child %>
          <% else %>
            <% break%>
          <% end %>
        <% end %>
        <% loop_counter.times do %>
        </ul>
      </li>
    <% end %>
  </ul>
  <form method='post' action='<%= comments_url %>'>
    <input 
        type='hidden'
        name='authenticity_token'
        value='<%= form_authenticity_token %>'>
    <input 
        type='hidden' 
        name=[comment][post_id] 
        value='<%= @comment.post_id %>'>
    <input 
        type='hidden' 
        name=[comment][parent_comment_id] 
        value='<%= @comment.latest_child.id %>'>
    <textarea id='content' name=[comment][content]></textarea>
    <button id='submit'>Create</button>
  </form>

app/views/layouts/_header.html.erb
<%= javascript_include_tag 'dropdown' %>
<i class="fa fa-reddit" aria-hidden="true"></i>
<input type='text'>
<section id='user-options'>
  <i class="fa fa-user" aria-hidden="true"></i>
  <i class="fa fa-caret-down" aria-hidden="true"></i>
</section>
<% if logged_in? %>
  <ul id='dropdown'>
    <li>
      Welcome <%= current_user.username%>
    </li>
    <li>
      <%= link_to 'Log Out', session_url(current_user.id), method: :delete %>
    </li>
  </ul>
<% else %>
  <ul id='dropdown'>
    <li>
      <a id='login' href='<%= new_session_url %>'>Log In</a>
    </li>
    <li>
      <a id='signup' href='<%= new_user_url %>'>Sign Up</a>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditOnRails</title>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'reset' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'header.scss.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render partial: 'layouts/header' %>
    </header>
    <br>
    <% flash.each do |type, msg| %>
      <%= msg %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<form method='post' action='<%= post_url(@post.id) %>'>
  <input type='hidden' name='_method' value='put'>
  <input 
    type='hidden' 
    name='authenticity_token' 
    value='<%= form_authenticity_token %>'>
  <input type='text' id='title' name=[post][title] value=<%= @post.title %>>
  <input type='text' id='url' name=[post][url] value=<%= @post.url %>>
  <input type='text' id='content' name=[post][content] value=<%= @post.content %>>
  <h2>Select Cross Post Associations</h2>
  <% Sub.all.each do |sub| %>
    <label><%= sub.title %></label>
    <input 
    id='subID'
    name='[post][sub_ids][]' 
    type='checkbox' 
    value='<%= sub.id %>'
    <%= 'checked' if @post.sub_ids.include?(sub.id) %>
    />
<br>
<% end %>
<button>Edit Post</button>
</form>

app/views/posts/new.html.erb
<form method='post' action='<%= sub_posts_url %>'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token%>'>
  <input id='title' type='text' name=[post][title]>
  <input id='url' type='text' name=[post][url]>
  <input id='content' type='text' name=[post][content]>
  <button>Create Post</button>
</form>

app/views/posts/show.html.erb
<section class='post'>
  <section class='post-info'>
    <h2><a><%= @post.title %></h2>
      <p><%= @post.author.username %></p>
    </section>
    <%= @post.url %>
    <p class='post-content'><%= @post.content %></p>
    <a href='<%= new_post_comment_url(@post) %>'>Leave a Comment</a>
  </section>
  <h3>Comments</h3>
  <% @all_comments[nil].each do |comment| %>
    <ul class='comment-chain'>
      <li>
        <%= 
        render partial: "comments/comment", 
        object: comment
      %>
        <a id='expand' href='<%= comment_url(comment) %>'>View comment</a>
        <% @all_comments[comment[:id]].each do |child_comment| %>
          <ul>
            <li>
              <%= 
                render partial: "comments/comment", 
                locals: {comment: child_comment}
              %>
            </li>
          <% end %>
        </ul>
      </ul>
    <% end %>

app/views/subs/edit.html.erb
<form method='post' action='<%= sub_url(@sub.id) %>'>
  <input type="hidden" name="_method" value="patch">
  <input type='hidden' 
    name='authenticity_token' 
    value='<%=form_authenticity_token%>'>
  <input type='text' id='title' name=[sub][title] value='<%= @sub.title %>'>
  <input type='text' id='description' name=[sub][description] value='<%= @sub.description %>'>
  <button id='edit'>Edit<button>
    </form>

app/views/subs/index.html.erb
<% if logged_in? %>
  <a href='<%= new_sub_url %>'>Create Sub</a>
<% end %>
<h2>All Subs</h2>
<% Sub.all.each do |sub| %>
  <% User.find(sub.moderator_id) %>
  <section>
    <h3><a href='<%= sub_url(sub) %>'><%= sub.title %></a></h3>
    <br>
    <%= sub.description %>
  </section>
<% end %>

app/views/subs/new.html.erb
<form method='post' action='<%= subs_url %>'>
  <input type='hidden' 
    name='authenticity_token' 
    value=<%= form_authenticity_token %>>
  <input name=[sub][title] id='title'>
  <input name=[sub][description] id='description'>
  <button>Create</button>
</form>

app/views/subs/show.html.erb
<a href='<%= edit_sub_url %>'>Edit Sub</a>
<h2><%= @sub.title %></h2>
<%= @sub.description %>
<br>
<% posts = @sub.posts.all %>
<% posts.each do |post| %>
  <a href='<%= post_url(post) %>'>
    <h3><%= post.title %></h3>
  </a>
  <br>
  <%= post.content[0..10] %>
  <br>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<form method='post' action=<%= users_url %>>
  <input type='hidden' 
    name='authenticity_token' 
    value=<%= form_authenticity_token%>>
  <label for='username'>Username:</label>
  <input type='text' name='[user][username]' id='username'>
  <label for='password'>Password:</label>
  <input type='text' name='[user][password]' id='password'>
  <button>Create User</button>
</form>

app/views/users/show.html.erb
<h2>Show page</h2>